# Generated by Django 5.0.3 on 2024-03-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupeTontine', '0002_rename_montant_groupetontine_montantcotisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupetontine',
            name='dateFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
