# Generated by Django 5.0.3 on 2024-04-01 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupeTontine', '0003_alter_groupetontine_datefin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupetontine',
            old_name='user',
            new_name='auteur',
        ),
    ]
