# Generated by Django 5.0.3 on 2024-04-02 02:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupeTontine', '0004_rename_user_groupetontine_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupetontine',
            name='dateDebut',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
