# Generated by Django 5.0.3 on 2024-04-25 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroupeTontine', '0005_groupetontine_datedebut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=150)),
                ('adress', models.DateTimeField(auto_now_add=True)),
                ('idGroupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroupeTontine.groupetontine')),
            ],
        ),
    ]
