# Generated by Django 5.0.3 on 2024-04-25 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupeTontine', '0006_membre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='nom',
            new_name='name',
        ),
    ]
