# Generated by Django 5.0.3 on 2024-05-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupeTontine', '0008_membre_iduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='idGroupe',
            new_name='participation',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='idUser',
        ),
    ]
