# Generated by Django 5.0.3 on 2024-05-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroupeTontine', '0009_rename_idgroupe_membre_participation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membre',
            old_name='participation',
            new_name='group',
        ),
    ]
